# Generated by Django 6.0.4 on 2026-04-10 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_remove_lead_assigned_to_lead_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='whatsapp_number',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='available_to_everyone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='car_plate_no',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='car_year',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='emirates_of_visa',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_uae_resident',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='need_car_insurance',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='salary_scale',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='source_form',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='visa_status',
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(default='Assigned', help_text='Current pipeline stage', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='delivery_channel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_pep',
            field=models.BooleanField(default=False, verbose_name='PEP Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='occupation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified'),
        ),
    ]
