# Generated by Django 6.0.4 on 2026-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_lead_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lead',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.AddField(
            model_name='lead',
            name='insurance_type',
            field=models.CharField(blank=True, choices=[('car_insurance_new', 'Car Insurance New'), ('car_insance_renewal', 'Car Insurance Renewal'), ('fleet_new', 'Fleet New'), ('fleet_renewal', 'Fleet Renewal')], max_length=255, null=True, verbose_name='Insurance_type'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('call', 'Call')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('comprehensive_agency', 'Comprehensive - Agency'), ('comprehensive_non_agency', 'Comprehensive - Non Agency'), ('third_party', 'Third Party')], max_length=255, null=True, verbose_name='subtype'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='delivery_channel',
            field=models.CharField(blank=True, choices=[('agent', 'Agent'), ('direct', 'Direct')], max_length=255, null=True, verbose_name='Lead Source'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='is_pep',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default=False, verbose_name='PEP Status'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='product_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('motor', 'Motor'), ('health', 'Health')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new_lead', 'New Lead'), ('assigned', 'Assigned'), ('non_contactable_1', 'Non Contactable 1'), ('non_contactable_2', 'Non Contactable 2'), ('non_contactable_3', 'Non Contactable 3'), ('contactable', 'Contactable'), ('requirement_gathering', 'Requirement Gathering'), ('sales_qualified_lead', 'Sales Qualified Lead')], default='Assigned', help_text='Current pipeline stage', max_length=100),
        ),
        migrations.DeleteModel(
            name='InsuranceInfo',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
