# Generated by Django 6.0.4 on 2026-04-22 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('leads', '0016_remove_note_created_by_remove_note_lead_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_lists', models.TextField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('emirates_id', models.CharField(blank=True, max_length=100, null=True)),
                ('id_expiry_dt', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('emirate', models.CharField(blank=True, max_length=100, null=True)),
                ('license_no', models.CharField(blank=True, max_length=100, null=True)),
                ('license_from_dt', models.DateField(blank=True, null=True)),
                ('license_to_dt', models.DateField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=100, null=True)),
                ('reg_number', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_dt', models.DateField(blank=True, null=True)),
                ('plate_code', models.CharField(blank=True, max_length=50, null=True)),
                ('plate_source', models.CharField(blank=True, max_length=100, null=True)),
                ('tcf_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ncd_years', models.IntegerField(blank=True, null=True)),
                ('traffic_tran_type', models.CharField(blank=True, max_length=100, null=True)),
                ('is_veh_brand_new', models.BooleanField(default=False)),
                ('agency_repair', models.BooleanField(default=False)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('make_id', models.CharField(blank=True, max_length=100, null=True)),
                ('model_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trim_id', models.CharField(blank=True, max_length=100, null=True)),
                ('body_type_id', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_capacity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_gcc_spec', models.BooleanField(default=False)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('valuation_date', models.DateField(blank=True, null=True)),
                ('stage_id', models.IntegerField(choices=[(1, 'Potential Customer'), (2, 'Awaiting Additional Documents'), (3, 'Quotation'), (4, 'Follow up'), (5, 'High Value Leads'), (6, 'Hot/Responded'), (7, 'Documentation Request'), (8, 'Insurer Submission'), (9, 'Pending with Insurer'), (10, 'Payment Collection'), (11, 'Payment Pending'), (12, 'Payment Done'), (13, 'Policy Issuance'), (14, 'Billing'), (15, 'Lost Cases & Future Prospects')], default=1)),
                ('additional_field', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='leads.lead')),
            ],
        ),
        migrations.CreateModel(
            name='DealDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='deal_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deals.deal')),
            ],
        ),
        migrations.DeleteModel(
            name='Deals',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
