# Generated by Django 6.0.4 on 2026-04-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CooperativeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licence_type', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=150)),
                ('trade_licence_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('po_box', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('first_business_date', models.DateField(blank=True, null=True)),
                ('insured_name', models.CharField(blank=True, max_length=150, null=True)),
                ('resident', models.BooleanField(default=False)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_incorporation', models.DateField(blank=True, null=True)),
                ('company_activity', models.TextField(blank=True, null=True)),
                ('aml_trace', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cooperative_customers',
            },
        ),
        migrations.CreateModel(
            name='IndividualCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('emirates_id', models.CharField(blank=True, max_length=50, null=True)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('resident', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'individual_customers',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COOPERATIVE', 'Cooperative')], max_length=20)),
                ('producer', models.CharField(blank=True, max_length=100, null=True)),
                ('main_customer', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_channel', models.CharField(blank=True, max_length=100, null=True)),
                ('pep', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('visa', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('policy_documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('policy_schedule', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('credit_note', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('debit_note', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('other_documents', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('system_generated_1', models.BooleanField(default=False)),
                ('system_generated_2', models.BooleanField(default=False)),
                ('system_generated_3', models.BooleanField(default=False)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='StatusOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pending_at', models.CharField(max_length=100)),
                ('assigned_user', models.CharField(max_length=100)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='invoice.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('direct_payment', models.BooleanField(default=False)),
                ('insurer_name', models.CharField(max_length=150)),
                ('invoice_date', models.DateField()),
                ('policy_start_date', models.DateField()),
                ('policy_end_date', models.DateField()),
                ('premium_currency', models.CharField(max_length=10)),
                ('amount_currency', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=100)),
                ('center', models.CharField(max_length=100)),
                ('policy_type', models.CharField(max_length=100)),
                ('policy_cover', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('net_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('charges', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurer_reference', models.CharField(max_length=100)),
                ('policy_number', models.CharField(max_length=100)),
                ('tax_invoice_number', models.CharField(max_length=100)),
                ('commission_invoice_number', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='invoice.invoice')),
            ],
        ),
    ]
