# Generated by Django 6.0.4 on 2026-04-11 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooperativecustomer',
            name='invoice',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cooperative', to='invoice.invoice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualcustomer',
            name='invoice',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='individual', to='invoice.invoice'),
            preserve_default=False,
        ),
    ]
