# Generated by Django 6.0.4 on 2026-04-16 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_cooperativecustomer_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_id', models.CharField(max_length=20, unique=True)),
                ('policy_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('insurer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('mismatch', 'Mismatch'), ('partial', 'Partial Match'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='mismatch', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='invoice.invoice')),
            ],
            options={
                'db_table': 'reconciliations',
            },
        ),
        migrations.CreateModel(
            name='UBODetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('eid_passport', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubo_details', to='invoice.invoice')),
            ],
        ),
    ]
