# Generated by Django 6.0.4 on 2026-04-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_reconciliation_ubodetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperativecustomer',
            name='aml_trace',
        ),
    ]
