# Generated by Django 6.0.4 on 2026-04-16 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Policys', '0001_initial'),
        ('invoice', '0004_remove_cooperativecustomer_aml_trace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='system_generated_1',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='system_generated_2',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='system_generated_3',
        ),
        migrations.RemoveField(
            model_name='reconciliation',
            name='policy_number',
        ),
        migrations.AddField(
            model_name='reconciliation',
            name='policy',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='Policys.policy'),
            preserve_default=False,
        ),
    ]
