# Generated by Django 6.0.4 on 2026-04-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_attachment_system_generated_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliation',
            name='statement_file',
            field=models.FileField(blank=True, null=True, upload_to='reconciliation_files/'),
        ),
    ]
