# Generated by Django 6.0.4 on 2026-04-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_reconciliation_statement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='credit_note_tax_invoice',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='policy_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='wording',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
